defaults:
  - _self_
  - model: sarimax #random_forest #sarimax #
  - metrics

train_dataset: Bitcoin
valid_dataset: Bitcoin
load_path:
save_dir: ./save1
dataset_path:
window_size: 1
train_start_date: 2016-11-24 09:30:00
train_end_date: 2021-11-24 10:30:00
valid_start_date: 2021-11-24 10:30:00
valid_end_date: 2022-11-24 10:30:00