defaults:
  - _self_

train_dataset: Bitcoin
valid_dataset: Bitcoin
load_path: False
dataset_path:
train_start_date: 2019-11-24 09:30:00
train_end_date: 2021-11-24 10:30:00
valid_start_date: 2021-11-24 10:30:00
valid_end_date: 2022-11-24 10:30:00
