defaults:
  - _self_
  - model: random_forest #orbit #random_forest #sarimax #
  - dataset: Bitcoin
  - metrics

validation_method: cross_validation
load_path: C:/Users/samen/Desktop/term9/forecasting/code/Data/hourly/XBTUSD-1h-data.csv
save_dir:
dataset_path:

