window_size: 1
train_start_date: 2016-11-24 09:30:00
train_end_date: 2021-11-24 10:30:00
valid_start_date: 2021-11-24 10:30:00
valid_end_date: 2022-11-24 10:30:00
features: Date, open, High, Low, close, trades, volume #make sure to have Date High Low
